version: '3.3'
services:
  brawl-stars-app:
    ports:
      - '8080:8080'
    build:
      context: ./
    container_name: brawl-stars-app
    volumes:
      - ./:/myapp
    image: brawl-stars-app
    environment:
      - CHOKIDAR_USEPOLLING=true